require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.6.0

Style/HashSyntax:
  Exclude:
    - 'lib/easy_hubspot/client.rb'

Naming/AccessorMethodName:
  Enabled: false
  Include:
    - 'lib/easy_hubspot/client.rb'

Layout/LineLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/StringLiterals:
  Exclude:
    - 'lib/easy_hubspot/base.rb'